# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:5.5.0

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu

#COPY elasticsearch-analysis-ansj-5.5.0.0-release.zip /usr/share/elasticsearch


#RUN /usr/share/elasticsearch/bin/elasticsearch-plugin install file:///usr/share/elasticsearch/elasticsearch-analysis-ansj-5.5.0.0-release.zip